language: ruby
rvm:
- 2.0.0
before_script:
- bundle exec compass compile
- bundle exec jekyll build
- npm install -g casperjs
- phantomjs --version
- casperjs --version
script:
- "casperjs test ./_scripts/phantom_testrunner.js"
after_success:
- "./_scripts/travis_deploy.sh"
branches:
  only:
  - master
  - live
env:
  global:
  - secure: YjpZsU4rVDqn0/+EtTLzJHWyvAavWBuUMHK1ttYaRTwaO7PYgy32t3BAwYGmJRWerlJ8W3T1JV04CbDpWF+/s2ZaXgAq4A27G+61J23CtECwXWSpTbGct+kowyQ8srH4Dx5i7wPiRPen5VL1I4u5nxEqIfHk3yqsMWGq/cVifMk=
  - secure: K60pRLkpoH4mqxCsQj68oNrkoRhi9NTiQ9VT0Vs+vmH7PE0JAhRkyXn9INk+hbgUnO9lQoK5BmAjJl8I5T20gtPLsf3H0zMfB85prWGKgtc3mTop1AsTbvrqgDpgUGT4iTfiwHH3eiFCuqfd0oWMT4a5qFi6TCb3CcHG7rKVHig=
notifications:
  hipchat:
    rooms:
      secure: LRVVBQ9ehtZnClIzWUyN24Zw/YzZd+4bSmCAUJp8egwgtWAIoPTAwO8MLCjEZPUVs5e2HcsbYh+7AEkH1pklDx3jVS07S2slqshuzeVkqACN5pCCo/r6tvISD6YG/NUKXmcSeCNxvcDKZXWHi9pi8bSFKne+C2nTSCHuX54TwIs=
