name: ThinkShout
description: ThinkShout - We provide web strategy and open source technology to forward-thinking organizations.
markdown: redcarpet
pygments: true

baseurl: /thinkshout
url: http://thinkshout.com

# Permalink Configuration
permalink: /blog/:year/:month/:title

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'bower.json', '.bowerrc', 'config.rb', 'sass']

# Team directory used by the data_to_pages plugin.
team_dir: 'team'
contact_redirect: 'thanks'

paginate: 10
paginate_path: "blog/page:num"

# Setting relative permalink to false. See http://jekyllrb.com/docs/upgrading/.
relative_permalinks: false

# Settings for sitemap_generator plugin.
sitemap:
    exclude:
        - "/rss.xml"
        - "/tag"
    include_posts:
        - "/index.html"
        - "/blog/index.html"
        - "/work/index.html"
        - "/careers/index.html"