name: ThinkShout
description: ThinkShout - We provide web strategy and open source technology to forward-thinking organizations.
kramdown:
  input: GFM
highlighter: rouge
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

baseurl: ''
url: http://thinkshout.com

# Permalink Configuration
permalink: /blog/:year/:month/:title

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'bower.json', '.bowerrc', 'config.rb', 'sass', 's3_website*.yml', 'stage_config']

# Team directory used by the data_to_pages plugin.
team_dir: 'team'
contact_redirect: 'thanks'
tag_dir: 'blog/category'

# Blog pagination.
# paginate: 10
# paginate_path: "blog/page:num"

# Setting relative permalink to false. See http://jekyllrb.com/docs/upgrading/.
relative_permalinks: false

# Settings for sitemap_generator plugin.
sitemap:
    exclude:
        - "/rss.xml"
        - "/tag"
    include_posts:
        - "/index.html"
        - "/blog/index.html"
        - "/work/index.html"
        - "/careers/index.html"

# Setting for prose.io
prose:
  ignore:
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
    - /_plugins
    - /_scripts
    - /assets
    - /sass
    - /expertise
    - /team
    - s3_website.yml
    - s3_website_stage.yml
    - rss.xml
    - robots.txt
    - Rakefile
    - config.rb
    - _config.yml
    - .gitignore
    - .bowerrc
    - Gemfile
  siteurl: "http://thinkshout.com"
  media: "assets/images/blog"
  metadata:
    blog:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "author"
        field:
          element: "text"
          label: "Author short name"
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured"
          help: "The top 3 featured posts will appear on the home page."
      - name: "short"
        field:
          element: "text"
          label: "Short teaser"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          help: "Enter one or more tags to categorize your post, E.g., Drupal, nonprofit, RedHen."
          alterable: true
    careers:
      - name: "layout"
        field:
          element: "hidden"
          value: "job"
      - name: "mailto"
        field:
          element: "text"
          label: "Email address for job submissions."
    work:
      - name: "layout"
        field:
          element: "hidden"
          value: "project"

# Case Study collection
collections:
  case_studies:
    output: true
    permalink: /:path/
  team:
    output: true
