name: ThinkShout
description: ThinkShout - We provide web strategy and open source technology to forward-thinking organizations.
kramdown:
  input: GFM
highlighter: rouge
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

baseurl: '/thinkshout'
url: 'http://thinkshout.github.io'

# Permalink Configuration
permalink: /blog/:year/:month/:title

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'bower.json', '.bowerrc', 'config.rb', 'sass', 's3_website*.yml', 'stage_config']

# Team directory used by the data_to_pages plugin.
team_dir: 'team'
contact_redirect: 'thanks'
tag_dir: 'blog/category'

# Blog pagination.
# paginate: 10
# paginate_path: "blog/page:num"

# Setting relative permalink to false. See http://jekyllrb.com/docs/upgrading/.
relative_permalinks: false

# Settings for sitemap_generator plugin.
sitemap:
    exclude:
        - "/rss.xml"
        - "/tag"
    include_posts:
        - "/index.html"
        - "/blog/index.html"
        - "/work/index.html"
        - "/careers/index.html"

# Case Study collection
collections:
  case_studies:
    output: true
    permalink: /work/:slug/
  expertise:
    output: true
    permalink: /expertise/:slug/
  team:
    output: true
    permalink: /team/:slug/
