name: ThinkShout
description: ThinkShout - We provide web strategy and open source technology to forward-thinking organizations.
kramdown:
  input: GFM
highlighter: rouge
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

baseurl: ''
url: https://thinkshout.com

# Permalink Configuration
permalink: /blog/:year/:month/:title/

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'package.json', 'config.rb', 'sass', 's3_website*.yml', 'stage_config', 'Guardfile']

# Team directory used by the data_to_pages plugin.
team_dir: 'team'
contact_redirect: 'thanks'
tag_dir: 'blog/category'

# Blog pagination.
plugins: [jekyll-paginate]
paginate: 13
paginate_path: "blog/page:num"

category_dir: "blog"
category_layout: "index.html"

# Setting relative permalink to false. See http://jekyllrb.com/docs/upgrading/.
relative_permalinks: false

# Settings for sitemap_generator plugin.
sitemap:
    exclude:
        - "/rss.xml"
        - "/tag"
    include_posts:
        - "/index.html"
        - "/blog/index.html"
        - "/work/index.html"
        - "/careers/index.html"
        - "/wonderlab/index.html"

# Collections
collections:
  careers:
    output: true
    permalink: /careers/:slug/
  case_studies:
    output: true
    permalink: /work/:slug/
  services:
    output: true
    permalink: /services/:slug/
  team:
    output: true
    permalink: /team/:slug/
  topic:
    output: true
    permalink: /blog/topic/:slug/
  wonderlab:
    output: true
    permalink: /wonderlab/:categories/:slug/
